### ISSUE TITLE
Missing git tags for releases

### ISSUE THREAD

**Issue by merkys** [gilleain/signatures#3]
This repository lacks git tags for releases. As a result, it is difficult to find out which commit refers to which release. Moreover, git tags would allow downloading release tarballs.

**Comment by merkys** [comment]
The commit 78af777fa70b18e1e895db8371ad045dea1d30c1 seems to be the one corresponding to the latest release, v1.1. Thus the following command line commands should be enough to tag the most recent release:
```bash
git tag --sign v1.1 78af777fa70b18e1e895db8371ad045dea1d30c1
git push --tags
```

**Comment by gilleain** [comment]
Thanks @merkys  - Finally got round to doing this

**Comment by merkys** [comment]
Great, thanks a lot @gilleain!
